// kai_probe — measure KleidiAI int4 matmul microkernels directly.
//
// WHY THIS EXISTS
// ---------------
// scripts/02_batch_sweep.sh infers kernel behaviour through llama.cpp, which
// carries confounds: threading, KV cache growth, graph scheduling, tokenizer
// cost. This removes the middle. It packs matrices and calls the microkernel in
// a loop, sweeping M — the row count, which in a forward pass is the number of
// tokens processed together.
//
// THE MEASUREMENT
// ---------------
// Every KleidiAI matmul variant has a row granularity `mr`. A kernel with mr=8
// processes 8 rows per macro-tile. Decode runs at M=1, so it invokes an 8-row
// kernel to compute one row. `mr` is an API call, not a benchmark, so the
// structural claim is exact; the timing sweep quantifies what it costs and finds
// where an i8mm variant overtakes a dotprod one.
//
// CORRECTNESS
// -----------
// A microkernel handed mis-packed inputs will happily return fast garbage. So
// every variant is cross-checked against every other at each shape: they compute
// the same mathematical product, so they must agree. Disagreement fails the run
// rather than reporting a number.
//
// The variant table is generated by tools/gen_variants.py from the KleidiAI
// checkout — see kai_variants.inc — so this file never hardcodes kernel names.

#include <algorithm>
#include <cfloat>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <random>
#include <string>
#include <vector>

// Packing kernels shared by every variant in this family.
#include "kai_lhs_quant_pack_qai8dxp_f32.h"
#include "kai_rhs_pack_nxk_qsi4cxp_qs4cxs1s0.h"

// GENERATED: #includes for each discovered variant, plus KAI_VARIANT_LIST.
#include "kai_variants.inc"

namespace {

// ---------------------------------------------------------------- variant table

struct Variant {
    const char* name;
    const char* isa;
    size_t (*get_mr)();
    size_t (*get_nr)();
    size_t (*get_kr)();
    size_t (*get_sr)();
    void (*run)(size_t m, size_t n, size_t k,
                const void* lhs_packed, const void* rhs_packed,
                float* dst, size_t dst_stride_row, size_t dst_stride_col,
                float clamp_min, float clamp_max);
};

const Variant kVariants[] = {
#define KAI_V(NAME, ISA)                            \
    {#NAME, ISA,                                    \
     kai_get_mr_matmul_##NAME,                      \
     kai_get_nr_matmul_##NAME,                      \
     kai_get_kr_matmul_##NAME,                      \
     kai_get_sr_matmul_##NAME,                      \
     kai_run_matmul_##NAME},
    KAI_VARIANT_LIST
#undef KAI_V
};

constexpr size_t kNumVariants = sizeof(kVariants) / sizeof(kVariants[0]);

// ---------------------------------------------------------------- json helpers

std::string json_escape(const std::string& s) {
    std::string out;
    out.reserve(s.size() + 2);
    for (char c : s) {
        if (c == '"' || c == '\\') { out += '\\'; out += c; }
        else if (c == '\n') { out += "\\n"; }
        else { out += c; }
    }
    return out;
}

// ---------------------------------------------------------------- test data

// RHS is int4, two nibbles per byte, n*k values total. Scales are per output
// channel (n of them). This mirrors how llama.cpp's Q4_0 weights arrive.
struct Problem {
    size_t n, k;
    std::vector<uint8_t> rhs_native;   // (n*k)/2 bytes
    std::vector<float> scales;         // n
    std::vector<float> bias;           // n
    std::vector<float> lhs;            // m*k, regenerated per m
};

Problem make_problem(size_t n, size_t k, uint32_t seed) {
    Problem p;
    p.n = n;
    p.k = k;
    std::mt19937 rng(seed);
    std::uniform_int_distribution<int> nib(0, 15);
    std::uniform_real_distribution<float> uf(0.02f, 0.08f);

    p.rhs_native.resize((n * k) / 2);
    for (auto& b : p.rhs_native) {
        b = static_cast<uint8_t>((nib(rng) << 4) | nib(rng));
    }
    p.scales.resize(n);
    for (auto& s : p.scales) s = uf(rng);
    p.bias.assign(n, 0.0f);
    return p;
}

std::vector<float> make_lhs(size_t m, size_t k, uint32_t seed) {
    std::mt19937 rng(seed);
    std::uniform_real_distribution<float> uf(-1.0f, 1.0f);
    std::vector<float> lhs(m * k);
    for (auto& v : lhs) v = uf(rng);
    return lhs;
}

// ---------------------------------------------------------------- one measurement

struct Sample {
    bool ok = false;
    double median_ns = 0.0;
    double gflops = 0.0;
    size_t mr = 0, nr = 0, kr = 0, sr = 0;
    std::string error;
};

double median_of(std::vector<double> v) {
    if (v.empty()) return 0.0;
    std::sort(v.begin(), v.end());
    const size_t mid = v.size() / 2;
    return (v.size() % 2) ? v[mid] : 0.5 * (v[mid - 1] + v[mid]);
}

Sample run_variant(const Variant& var, const Problem& prob,
                   const std::vector<float>& lhs, size_t m,
                   int reps, std::vector<float>& dst_out) {
    Sample s;
    const size_t n = prob.n, k = prob.k;

    s.mr = var.get_mr();
    s.nr = var.get_nr();
    s.kr = var.get_kr();
    s.sr = var.get_sr();

    const size_t lhs_packed_size =
        kai_get_lhs_packed_size_lhs_quant_pack_qai8dxp_f32(m, k, s.mr, s.kr, s.sr);
    const size_t rhs_packed_size =
        kai_get_rhs_packed_size_rhs_pack_nxk_qsi4cxp_qs4cxs1s0(n, k, s.nr, s.kr, s.sr);

    if (lhs_packed_size == 0 || rhs_packed_size == 0) {
        s.error = "packed size reported zero";
        return s;
    }

    std::vector<uint8_t> lhs_packed(lhs_packed_size);
    std::vector<uint8_t> rhs_packed(rhs_packed_size);
    dst_out.assign(m * n, 0.0f);

    kai_rhs_pack_nxk_qsi4cxp_qs4cxs1s0_params rhs_params;
    std::memset(&rhs_params, 0, sizeof(rhs_params));
    rhs_params.lhs_zero_point = 1;
    rhs_params.rhs_zero_point = 8;   // int4 stored biased by 8

    kai_run_rhs_pack_nxk_qsi4cxp_qs4cxs1s0(
        /*num_groups=*/1, n, k, s.nr, s.kr, s.sr,
        prob.rhs_native.data(),
        prob.bias.data(),
        prob.scales.data(),
        rhs_packed.data(),
        /*extra_bytes=*/0,
        &rhs_params);

    kai_run_lhs_quant_pack_qai8dxp_f32(
        m, k, s.mr, s.kr, s.sr, /*m_idx_start=*/0,
        lhs.data(), /*lhs_stride=*/k * sizeof(float),
        lhs_packed.data());

    const size_t dst_stride_row = n * sizeof(float);
    const size_t dst_stride_col = sizeof(float);
    // No clamping: we are timing the matmul, not exercising the activation.
    const float lo = -FLT_MAX, hi = FLT_MAX;

    // Warmup: first call pays page faults and cache cold-start.
    var.run(m, n, k, lhs_packed.data(), rhs_packed.data(), dst_out.data(),
            dst_stride_row, dst_stride_col, lo, hi);

    std::vector<double> times;
    times.reserve(static_cast<size_t>(reps));
    for (int r = 0; r < reps; ++r) {
        const auto t0 = std::chrono::steady_clock::now();
        var.run(m, n, k, lhs_packed.data(), rhs_packed.data(), dst_out.data(),
                dst_stride_row, dst_stride_col, lo, hi);
        const auto t1 = std::chrono::steady_clock::now();
        times.push_back(
            std::chrono::duration<double, std::nano>(t1 - t0).count());
    }

    s.median_ns = median_of(times);
    // 2 flops per multiply-accumulate.
    const double flops = 2.0 * static_cast<double>(m) *
                         static_cast<double>(n) * static_cast<double>(k);
    s.gflops = (s.median_ns > 0.0) ? (flops / s.median_ns) : 0.0;
    s.ok = true;
    return s;
}

// Two variants computing the same product must agree. Tolerance is loose
// because int4 packing layouts differ between variants, but a packing bug
// produces errors orders of magnitude beyond this.
bool agrees(const std::vector<float>& a, const std::vector<float>& b,
            double tol, double* worst) {
    if (a.size() != b.size()) return false;
    double w = 0.0;
    for (size_t i = 0; i < a.size(); ++i) {
        const double d = std::fabs(static_cast<double>(a[i]) - static_cast<double>(b[i]));
        const double scale = std::max(1.0, std::fabs(static_cast<double>(a[i])));
        w = std::max(w, d / scale);
    }
    *worst = w;
    return w <= tol;
}

}  // namespace

int main(int argc, char** argv) {
    size_t n = 4096, k = 4096;
    int reps = 20;
    std::string out_path;
    std::vector<size_t> m_sweep = {1, 2, 3, 4, 6, 8, 12, 16, 24, 32, 64};

    for (int i = 1; i < argc; ++i) {
        const std::string a = argv[i];
        auto next = [&]() -> const char* { return (i + 1 < argc) ? argv[++i] : nullptr; };
        if (a == "--n") { if (const char* v = next()) n = std::strtoul(v, nullptr, 10); }
        else if (a == "--k") { if (const char* v = next()) k = std::strtoul(v, nullptr, 10); }
        else if (a == "--reps") { if (const char* v = next()) reps = std::atoi(v); }
        else if (a == "--out") { if (const char* v = next()) out_path = v; }
        else if (a == "--help") {
            std::printf("usage: kai_probe [--n N] [--k K] [--reps R] [--out FILE]\n");
            return 0;
        }
    }

    if (kNumVariants == 0) {
        std::fprintf(stderr, "kai_probe: no variants compiled in — "
                             "check tools/gen_variants.py output\n");
        return 1;
    }
    if ((n * k) % 2 != 0) {
        std::fprintf(stderr, "kai_probe: n*k must be even (int4 packs 2 per byte)\n");
        return 1;
    }

    std::fprintf(stderr, "kai_probe: %zu variants, n=%zu k=%zu reps=%d\n",
                 kNumVariants, n, k, reps);

    const Problem prob = make_problem(n, k, 1234u);

    std::string json = "{\n  \"schema\": \"specarm.kai_probe/1\",\n";
    json += "  \"n\": " + std::to_string(n) + ",\n";
    json += "  \"k\": " + std::to_string(k) + ",\n";
    json += "  \"reps\": " + std::to_string(reps) + ",\n";
    json += "  \"variants\": [\n";

    // Geometry first: this is the structural finding and needs no timing.
    for (size_t v = 0; v < kNumVariants; ++v) {
        const Variant& var = kVariants[v];
        json += "    {\"name\": \"" + json_escape(var.name) + "\"";
        json += ", \"isa\": \"" + json_escape(var.isa) + "\"";
        json += ", \"mr\": " + std::to_string(var.get_mr());
        json += ", \"nr\": " + std::to_string(var.get_nr());
        json += ", \"kr\": " + std::to_string(var.get_kr());
        json += ", \"sr\": " + std::to_string(var.get_sr());
        json += "}";
        json += (v + 1 < kNumVariants) ? ",\n" : "\n";
        std::fprintf(stderr, "  %-64s isa=%-8s mr=%zu nr=%zu\n",
                     var.name, var.isa, var.get_mr(), var.get_nr());
    }
    json += "  ],\n  \"measurements\": [\n";

    bool first_row = true;
    int mismatches = 0;

    for (const size_t m : m_sweep) {
        const std::vector<float> lhs = make_lhs(m, k, 99u + static_cast<uint32_t>(m));

        std::vector<std::vector<float>> outputs(kNumVariants);
        std::vector<Sample> samples(kNumVariants);

        for (size_t v = 0; v < kNumVariants; ++v) {
            samples[v] = run_variant(kVariants[v], prob, lhs, m, reps, outputs[v]);
        }

        // Cross-variant agreement: same product, so same answer.
        size_t ref = kNumVariants;
        for (size_t v = 0; v < kNumVariants; ++v) {
            if (samples[v].ok) { ref = v; break; }
        }
        for (size_t v = 0; v < kNumVariants; ++v) {
            if (!samples[v].ok || v == ref || ref == kNumVariants) continue;
            double worst = 0.0;
            if (!agrees(outputs[ref], outputs[v], 1e-2, &worst)) {
                std::fprintf(stderr,
                             "  MISMATCH m=%zu %s vs %s (worst rel err %.3g)\n",
                             m, kVariants[ref].name, kVariants[v].name, worst);
                samples[v].ok = false;
                samples[v].error = "disagrees with reference variant";
                ++mismatches;
            }
        }

        for (size_t v = 0; v < kNumVariants; ++v) {
            const Sample& s = samples[v];
            // Rows actually used out of the rows the kernel's tile provides.
            const size_t mr = s.mr ? s.mr : 1;
            const size_t tiles = (m + mr - 1) / mr;
            const double utilization =
                static_cast<double>(m) / static_cast<double>(tiles * mr);

            if (!first_row) json += ",\n";
            first_row = false;
            json += "    {\"m\": " + std::to_string(m);
            json += ", \"variant\": \"" + json_escape(kVariants[v].name) + "\"";
            json += ", \"isa\": \"" + json_escape(kVariants[v].isa) + "\"";
            json += ", \"ok\": " + std::string(s.ok ? "true" : "false");
            json += ", \"mr\": " + std::to_string(s.mr);
            json += ", \"row_utilization\": " + std::to_string(utilization);
            json += ", \"median_ns\": " + std::to_string(s.median_ns);
            json += ", \"gflops\": " + std::to_string(s.gflops);
            if (!s.error.empty()) {
                json += ", \"error\": \"" + json_escape(s.error) + "\"";
            }
            json += "}";
        }

        // Progress line: best variant at this m.
        size_t best = 0;
        for (size_t v = 1; v < kNumVariants; ++v) {
            if (samples[v].ok && samples[v].gflops > samples[best].gflops) best = v;
        }
        std::fprintf(stderr, "  m=%-4zu best=%-8s %.2f GFLOP/s\n",
                     m, kVariants[best].isa, samples[best].gflops);
    }

    json += "\n  ],\n  \"mismatches\": " + std::to_string(mismatches) + "\n}\n";

    if (!out_path.empty()) {
        FILE* f = std::fopen(out_path.c_str(), "w");
        if (!f) {
            std::fprintf(stderr, "kai_probe: cannot write %s\n", out_path.c_str());
            return 1;
        }
        std::fwrite(json.data(), 1, json.size(), f);
        std::fclose(f);
        std::fprintf(stderr, "kai_probe: wrote %s\n", out_path.c_str());
    } else {
        std::fputs(json.c_str(), stdout);
    }

    if (mismatches > 0) {
        std::fprintf(stderr,
                     "kai_probe: %d variant mismatches — timings are not "
                     "trustworthy until packing is correct\n", mismatches);
        return 2;
    }
    return 0;
}
