#!/usr/bin/env python3
"""
gen_variants.py — generate the KleidiAI microkernel variant table from a checkout.

Microkernel variant names move between KleidiAI releases. Hardcoding a list means
the probe breaks on upgrade with a confusing linker error. Instead we scan the
checkout for the headers that are actually present and emit an X-macro list, so
the probe always builds against exactly the variants that exist.

Emits `kai_variants.inc`:

    #include "kai_matmul_clamp_f32_..._neon_i8mm.h"
    #define KAI_VARIANT_LIST \\
      KAI_V(clamp_f32_..._neon_i8mm, "i8mm") \\
      ...

Run:  python3 tools/gen_variants.py <kleidiai_root> <output.inc>
"""

from __future__ import annotations

import os
import re
import sys

# Matmul family the probe targets: f32 output, dynamically-quantized int8 LHS,
# channelwise int4 RHS. This is the shape llama.cpp's Q4_0 path uses.
FAMILY = "matmul_clamp_f32_qai8dxp_qsi4cxp"
HEADER_RE = re.compile(r"^kai_matmul_(clamp_f32_qai8dxp\w+)\.h$")


def classify(name: str) -> str:
    """ISA path encoded in the variant name. Order matters: i8mm and sme
    variants also contain the substring 'neon'."""
    low = name.lower()
    for isa in ("sme2", "sme", "i8mm", "dotprod"):
        if isa in low:
            return isa
    return "neon" if "neon" in low else "other"


def discover(root: str) -> list[tuple[str, str]]:
    """Find variant headers, skipping internal/interface headers."""
    search = os.path.join(root, "kai", "ukernels", "matmul", FAMILY)
    if not os.path.isdir(search):
        # Fall back to a whole-tree walk: layout has changed before.
        search = root

    found: dict[str, str] = {}
    for dirpath, _dirnames, filenames in os.walk(search):
        for fn in filenames:
            m = HEADER_RE.match(fn)
            if not m:
                continue
            variant = m.group(1)
            # Interface/among-variant helper headers are not runnable kernels.
            if "interface" in variant or variant.endswith("_impl"):
                continue
            found[variant] = classify(variant)
    return sorted(found.items())


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    root, out_path = sys.argv[1], sys.argv[2]

    variants = discover(root)
    if not variants:
        print(f"gen_variants: no microkernel headers found under {root}", file=sys.stderr)
        print("  expected something like "
              f"{os.path.join(root, 'kai/ukernels/matmul', FAMILY)}", file=sys.stderr)
        return 1

    lines = [
        "// GENERATED by tools/gen_variants.py — do not edit.",
        f"// Discovered {len(variants)} microkernel variants.",
        "",
    ]
    for name, _isa in variants:
        lines.append(f'#include "kai_matmul_{name}.h"')
    lines += ["", "#define KAI_VARIANT_LIST \\"]
    for i, (name, isa) in enumerate(variants):
        cont = " \\" if i < len(variants) - 1 else ""
        lines.append(f'    KAI_V({name}, "{isa}"){cont}')
    lines.append("")

    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")

    by_isa: dict[str, int] = {}
    for _n, isa in variants:
        by_isa[isa] = by_isa.get(isa, 0) + 1
    summary = ", ".join(f"{k}:{v}" for k, v in sorted(by_isa.items()))
    print(f"gen_variants: {len(variants)} variants ({summary}) -> {out_path}")

    # The probe compares a GEMV-friendly path against a GEMM path. Without both
    # there is nothing to compare, so say so loudly rather than producing a
    # half-useful benchmark.
    if "i8mm" not in by_isa:
        print("gen_variants: WARNING no i8mm variants found — "
              "the crossover comparison needs them", file=sys.stderr)
    if "dotprod" not in by_isa:
        print("gen_variants: WARNING no dotprod variants found — "
              "no GEMV baseline to compare against", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
